### ISSUE TITLE
Login ignores userID in Authentication

### ISSUE THREAD

**Issue by domus71** [corbado/passkey-tutorial#2]
You must include the user.id in credentialService.getCredentialByCredentialId in handleLoginFinish function. 

If you have 2 logins from the same device, you must include the user.id in the database query.

In services/credentialService.ts (line 23)
`async getCredentialByCredentialId(credentialId: string, userID: string): Promise<AuthenticatorDevice | null> {
    try {
      const [rows] = await promisePool.query(
        "SELECT * FROM credentials WHERE credential_id = ? AND user_id = ? LIMIT 1",
        [credentialId, userID]
      );
...`

In controllers/authentication.ts (line 54)
`const dbCredential: AuthenticatorDevice | null = await credentialService.getCredentialByCredentialId(
      credentialID,
      loggedInUserId
    );`

Costis

**Comment by lukaskratzel** [comment]
I included your suggestion. Thank you for bringing the issue up :)
