### ISSUE TITLE
MySql errors and errors 

### ISSUE THREAD

**Issue by awlawl** [corbado/passkey-tutorial#3]
Thanks for your written tutorial blog post. It has been the best I've read so far!

I've pulled the repo but when I docker compose  MySql container cycles restarts over and over with this error:

db-1   | 2024-10-15 14:56:09+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 9.0.1-1.el9 started.
db-1   | 2024-10-15 14:56:10+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db-1   | 2024-10-15 14:56:10+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 9.0.1-1.el9 started.
db-1   | 2024-10-15 14:56:10+00:00 [Note] [Entrypoint]: Initializing database files
db-1   | 2024-10-15T14:56:10.182316Z 0 [System] [MY-015017] [Server] MySQL Server Initialization - start.
db-1   | 2024-10-15T14:56:10.182905Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 9.0.1) initializing of server in progress as process 79
db-1   | 2024-10-15T14:56:10.186353Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
db-1   | 2024-10-15T14:56:10.360700Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
**db-1   | 2024-10-15T14:56:11.276111Z 0 [ERROR] [MY-000067] [Server] unknown variable 'default-authentication-plugin=mysql_native_password'.**
**db-1   | 2024-10-15T14:56:11.277839Z 0 [ERROR] [MY-013236] [Server] The designated data directory /var/lib/mysql/ is unusable. You can remove all files that the server added to it.**
db-1   | 2024-10-15T14:56:11.277881Z 0 [ERROR] [MY-010119] [Server] Aborting

My guess is that since there is a specific version of the mysql contained specified in the compose file, this setup may not be compatible with the latest image. When I specify the image tag 8.0. It now starts up properly.

However now this line:
```const attestationResponse = await SimpleWebAuthnBrowser.startRegistration(options);```
throws this error:
```Error: Cannot read properties of undefined (reading 'challenge')```

I see in the browser console that this is what is in the options object:

```
{
    "challenge": "8OjFOksSksV0evSmgwJkW-kamfknJwcamByXOZ0zxoU",
    "rp": {
        "name": "Passkeys Tutorial",
        "id": "localhost"
    },
    "user": {
        "id": "8428e9b2-fa0d-44d7-b909-83b8c7587816",
        "name": "asdasd",
        "displayName": "asdasd"
    },
    "pubKeyCredParams": [
        {
            "alg": -7,
            "type": "public-key"
        },
        {
            "alg": -257,
            "type": "public-key"
        }
    ],
    "timeout": 60000,
    "attestation": "direct",
    "excludeCredentials": [],
    "authenticatorSelection": {
        "residentKey": "preferred",
        "requireResidentKey": false
    },
    "extensions": {
        "credProps": true
    }
}
```

I don't know enough about what that function expects or if the mysql issue is related or not.

This is on Chrome Version 129.0.6668.100 (Official Build) (arm64) on a Macbook.

**Comment by awlawl** [comment]
Ok the javascript error was also a "latest" version issue. The SimpleWebAuthn javascript file was getting the latest and 11.0 was released 2 days ago.

When I specified version 10, the demo works end-to-end again:
https://unpkg.com/@simplewebauthn/browser@10.0.0/dist/bundle/index.es5.umd.min.js

**Comment by vincentdelitz** [comment]
Thanks @awlawl, let me check if we need to pin the version or can adapt to 11.0 somehow

**Comment by lukaskratzel** [comment]
@awlawl Thank you very much for pointing the issue out. The issue was due to a new major version in the simplewebauthn browser library. I now pinned the version :)

**Comment by jai-charan** [comment]
Hey @lukaskratzel , I am still getting the error. Error: Cannot read properties of undefined (reading 'challenge') when i run the docker-compose. PS: This was runnning for me earlier and now I am getting this error.

**Comment by lukaskratzel** [comment]
Hello @jai-charan, I just tried to reproduce your issue, but everything is working fine for me. Do you mind sharing some more details about how to reproduce your issue?

**Comment by jai-charan** [comment]
I just cloned the repo and did docker-compose up.. Then when I try to register for passkeys..I am getting this error.

**Comment by awlawl** [comment]
I cloned from scratch, did a docker compose build, docker compose up, registered a new user and logged in with the new passkey. No issues. 

@jai-charan, one possibility might be that the image that docker compose is loading needs to be rebuilt. The image is stored in the docker system outside of the repo. Try removing the docker image "passkey-tutorial-app" and rebuilding from the repo.

**Comment by jai-charan** [comment]
That worked!! Thanks @awlawl . Maybe i was running the old image itself..
